
platform :ios, '9.0'

use_frameworks!

target 'FireBaseAuthFirst' do

pod 'Firebase/Core'
pod 'Firebase/Auth'

# These are pods used for the auth providers.
pod 'FBSDKLoginKit'
pod 'GoogleSignIn'

end
